#!/usr/bin/env bash


cd "$HOME"/Hämtningar
mkdir -p images
mkdir -p text_files
mkdir -p audio
mkdir -p pdfs

inotifywait -m -e close_write -e moved_to --format "%f" . | while
    read -r filename; do
    echo "$filename moved to Hämtningar"

case "$filename" in
    *.img|*.jpg|*.jpeg|*.bmp|*.gif) mv "$filename" images;;
    *.txt) mv "$filename" text_files;;
    

esac
done 
