#!/usr/bin/env bash


cd ~/Hämtningar

inotifywait -m -e close_write -e moved_to --format "%f" . | while IFS= read -r filename; do
        echo "$filename moved to Hämtningar"

case "$filename" in
    *.img|*.jpg|*.jpeg|*.png|*.gif) mkdir -p images && mv "$filename" images;;
    *.txt|*.md) mkdir -p text_files && mv "$filename" text_files;;
    *.aac|*.mp3|*.flac|*.waw) mkdir -p audio && mv "$filename" audio;;
    *.avi|*.mpg|*.mp4|*.flv) mkdir -p video && mv "$filename" video;;
    *.pdf|*.docx|*.xlsx|*.pptx|*.odt) mkdir -p documents && mv "$filename" documents;;
    *) mkdir -p other && mv "$filename" other;;
esac                                                    
                                                                                         done
